# Introdução ao Numpy - 4
## Leonardo Yves de Souza Melo
### (21)971771433 | prof.leoyves@gmail.com
## Fontes:
### 1) Python for Data Science Handbook - Jake VanderPlas; capítulo 2

# Bibliotecas

In [16]:
import numpy as np

## Indexação e partição de arrays

Lembrando sempre que a contagem no python começa no índice 0

In [17]:
np.random.seed(42)
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [18]:
display(x1,x2,x3)

array([6, 3, 7, 4, 6, 9])

array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4],
        [2, 6, 4, 8, 6]],

       [[1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3],
        [6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5]],

       [[5, 9, 3, 5, 1],
        [9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]])

In [4]:
x = np.arange(10)

In [5]:
# x[::2]   todos os elementos de índice par
# x[1::2]  todos os elementos de índice ímpar
x[::2],x[1::2]

(array([0, 2, 4, 6, 8]), array([1, 3, 5, 7, 9]))

In [6]:
# x[::-1]   todos os elementos na ordem reversa
# x[::-2]   todos os elementos de índice par na ordem reversa
# x[::-1][1::2]   todos os elementos de índice ímpar na ordem reversa
x[::-1],x[::-2],x[::-1][1::2]

(array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]),
 array([9, 7, 5, 3, 1]),
 array([8, 6, 4, 2, 0]))

In [7]:
# todos os elementos de índice par, considerando a partir do sexto elemento, na ordem reversa
x[5::-2]

array([5, 3, 1])

In [8]:
# x2 é uma matriz 3x4
## seleção das duas primeiras linhas e em cada linha, seleção dos três 
## primeiros elementos
x2[:2,:3]

array([[2, 6, 7],
       [3, 7, 7]])

In [9]:
# seleção das três primeiras linhas
# em cada linha seleção dos elementos de índice par
x2[:3,::2]

array([[2, 7],
       [3, 7],
       [5, 1]])

In [10]:
# a alteração em x2_sub acarreta numa alteração em x2
x2_sub = x2[:2,:2]
x2_sub[0,0] = 99
display(x2_sub,x2)

array([[99,  6],
       [ 3,  7]])

array([[99,  6,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])

In [11]:
# a utilização do método copy criou um novo objeto fazendo com que a alteração
# ficasse isolada
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy[0,0] = 42
display(x2_sub_copy,x2_sub,x2)

array([[42,  6],
       [ 3,  7]])

array([[99,  6],
       [ 3,  7]])

array([[99,  6,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])

In [12]:
x = np.arange(1,4)
y = x[::-1].copy()
z = np.ones_like(x)*99

display(x,y,z)

array([1, 2, 3])

array([3, 2, 1])

array([99, 99, 99])

In [13]:
# concatenação simples de dois ou mais arrays
display(np.concatenate([x,y]),np.concatenate([x,y,z]))

array([1, 2, 3, 3, 2, 1])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [14]:
grid = np.arange(1,7).reshape(2,3)
grid2 = np.arange(7,13).reshape(2,3)

display(grid,grid2)

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 7,  8,  9],
       [10, 11, 12]])

``axis=0``: conexão de cada linha preservando as colunas.<br>
``axis=1``: conexão de cada linha não preservando as colunas.

In [15]:
# concatenação simples de arrays multidimensionais
# axis=0 é default argument
np.concatenate([grid,grid2]),np.concatenate([grid,grid2],axis=1)

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]))