# Introdução ao Numpy - 1
## Leonardo Yves de Souza Melo
### (21)971771433 | prof.leoyves@gmail.com
## Fontes:
### 1) Python for Data Analysis - Wes McKinney; capítulo 4
### 2) Python for Finance - Yves Hilspisch; capítulo 4

# Bibliotecas

In [1]:
import numpy as np

## Construção de arrays

In [2]:
# vetor de 10 coordenadas inteiras variando entre 10 e 50
np.random.seed(42)
a = np.random.randint(10,50,10)

In [3]:
a

array([48, 38, 24, 17, 30, 48, 28, 32, 20, 20])

In [4]:
# soma de todas as coordenadas do array
a.sum()

305

In [5]:
# considerando o array uma amostra, retorna o valor do desvio padrão
a.std()

10.594810050208546

In [6]:
# soma cumulativa das coordenadas do array
a.cumsum()

array([ 48,  86, 110, 127, 157, 205, 233, 265, 285, 305], dtype=int32)

Abaixo, temos o array ``b``, construído a partir do array ``a``. Em que cada coordenada do array ``b``, é obtida por meio de operações matemáticas vetorizadas sobre o array ``a``. Sendo o array ``a`` a representação de um vetor de 10 coordenadas, o array ``b`` representa uma matriz, que tanto pode ser $3\times 10$, quanto $10\times 3$ no caso abaixo, o resultado foi uma matriz $3\times 10$

In [7]:
b = np.array([a,a*2,a/2])

In [8]:
b

array([[48. , 38. , 24. , 17. , 30. , 48. , 28. , 32. , 20. , 20. ],
       [96. , 76. , 48. , 34. , 60. , 96. , 56. , 64. , 40. , 40. ],
       [24. , 19. , 12. ,  8.5, 15. , 24. , 14. , 16. , 10. , 10. ]])

In [9]:
# selecionando todos os elementos da primeira componente do array 
# primeira linha da matriz
b[0]

array([48., 38., 24., 17., 30., 48., 28., 32., 20., 20.])

In [10]:
# duas formas diferentes de selecionar o terceiro elemento da primeira componente
# elemento da primeira e terceira coluna da matriz
b[0,2], b[0][2]

(24.0, 24.0)

In [11]:
# selecionando simultaneamente o segundo elemento das três componentes do array
# pensando matricialmente, é a escolha da segunda coluna da matriz 
b[:,1]

array([38., 76., 19.])

In [12]:
# soma dos elementos de cada coluna (axis=0 <--> coluna)
b.sum(axis=0)

array([168. , 133. ,  84. ,  59.5, 105. , 168. ,  98. , 112. ,  70. ,
        70. ])

In [13]:
# soma dos elementos de cada linha (axis=1 <--> linha)
b.sum(axis=1)

array([305. , 610. , 152.5])

In [14]:
# soma de todos os elementos das três componentes
b.sum(), b.sum(axis=1).sum(), b.sum(axis=0).sum()

(1067.5, 1067.5, 1067.5)

In [15]:
# array de 2 linhas e 3 colunas, com entradas nulas e do tipo float
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# array de 2 linhas e 3 colunas, com entradas nulas e do tipo integer 
np.zeros((2,3),dtype='i')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [17]:
# array de 2 linhas e 3 colunas, com entradas nulas do tipo bool
np.zeros((2,3),dtype='?')

array([[False, False, False],
       [False, False, False]])

In [18]:
# array com as mesmas dimensões do array b, com todas as entradas nulas
np.zeros_like(b)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
# array de 3 linhas e 2 colunas, com entradas unitárias 
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# array de 3 linhas e 2 colunas, com entradas unitárias e inteiras
np.ones((3,2),dtype='i')

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [21]:
# array de 3 linhas e 2 colunas, com entradas unitárias do tipo bool
np.ones((3,2),dtype='?')

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [22]:
# array representando a matriz identidade 3x3, com entradas do tipo float
np.eye(3),np.identity(3)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [23]:
# array representando a matriz identidade 3x3, com entradas do tipo bool
np.eye(3,dtype='?'),np.identity(3,dtype="?")

(array([[ True, False, False],
        [False,  True, False],
        [False, False,  True]]),
 array([[ True, False, False],
        [False,  True, False],
        [False, False,  True]]))

In [24]:
# array de 3 linhas e 5 colunas, com todas as entradas iguais
np.full((3,5),'léo yves')

array([['léo yves', 'léo yves', 'léo yves', 'léo yves', 'léo yves'],
       ['léo yves', 'léo yves', 'léo yves', 'léo yves', 'léo yves'],
       ['léo yves', 'léo yves', 'léo yves', 'léo yves', 'léo yves']],
      dtype='<U8')

array com o mesmo shape do array b, com todas as entradas iguais ao objeto presente no segundo argumento da função `np.full_like`

In [25]:
np.full_like(b,2)

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

## Reshape and resizing

In [26]:
x = np.random.randn(3,1) # vetor coluna, matriz 3x1
y = np.random.randn(3) # vetor do R^3
print(np.shape(x),np.shape(y))
x,y

(3, 1) (3,)


(array([[ 0.27904129],
        [ 1.01051528],
        [-0.58087813]]),
 array([-0.52516981, -0.57138017, -0.92408284]))

In [27]:
# verificação do formato do array
g = np.arange(15)
print(g.shape,np.shape(g))

(15,) (15,)


In [28]:
# transformação de um vetor do R^15 em uma matriz 3x5
g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
# matriz h com 5 linhas e 3 colunas, com os mesmos elementos de g
h = g.reshape((5,3))

In [30]:
# matriz h e a sua transposta h.T
h,h.T,h.transpose()

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[ 0,  3,  6,  9, 12],
        [ 1,  4,  7, 10, 13],
        [ 2,  5,  8, 11, 14]]),
 array([[ 0,  3,  6,  9, 12],
        [ 1,  4,  7, 10, 13],
        [ 2,  5,  8, 11, 14]]))

In [31]:
# transformação do vetor do R^15 em uma matriz 3x1 ignorando as outras entradas
np.resize(g,(3,1))

array([[0],
       [1],
       [2]])

In [32]:
# transformação do vetor do R^15 em uma matriz 1x5 ignorando as outras entradas
np.resize(g,(1,5))

array([[0, 1, 2, 3, 4]])

Em cada linha da matriz h foram adicionados os elementos referentes ao array `2*h`, deixando o array com shape (5,6). Também podemos pensar em termos de adição de colunas, como se a matriz `2*h` fosse simplesmente colada ao lado da matriz `h`.

`h.shape = (5,3)`

In [33]:
h,2*h,np.hstack((h,2*h)),np.hstack((h,2*h)).shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16],
        [18, 20, 22],
        [24, 26, 28]]),
 array([[ 0,  1,  2,  0,  2,  4],
        [ 3,  4,  5,  6,  8, 10],
        [ 6,  7,  8, 12, 14, 16],
        [ 9, 10, 11, 18, 20, 22],
        [12, 13, 14, 24, 26, 28]]),
 (5, 6))

Em cada coluna da matriz h foram adicionados os elementos referentes à matriz `0.5*h` deixando o array com shape (10,3). Podemos pensar que a matriz `0.5*h` foi colada no sentido vertical na matriz `h`.
`h.shape = (5,3)`

In [34]:
np.vstack((h,0.5*h)),np.vstack((h,0.5*h)).shape

(array([[ 0. ,  1. ,  2. ],
        [ 3. ,  4. ,  5. ],
        [ 6. ,  7. ,  8. ],
        [ 9. , 10. , 11. ],
        [12. , 13. , 14. ],
        [ 0. ,  0.5,  1. ],
        [ 1.5,  2. ,  2.5],
        [ 3. ,  3.5,  4. ],
        [ 4.5,  5. ,  5.5],
        [ 6. ,  6.5,  7. ]]),
 (10, 3))

In [35]:
# "planificação" da matriz seguindo as linhas 
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
# order='C' é o argumento default do método
# order='F' planifica a matriz indo pelas colunas
h.flatten(order='C'),h.flatten(order='F')

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14]))

In [37]:
# iterador normal, mostra cada linha 
for i in h:
    print(i)
# mostra os elementos do array planificado
for i in h.flat:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


## Indexação Booleana

In [38]:
# arrays booleanos
h>8, h<=7, h==5

(array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True, False],
        [False, False, False],
        [False, False, False]]),
 array([[False, False, False],
        [False, False,  True],
        [False, False, False],
        [False, False, False],
        [False, False, False]]))

In [39]:
# coverte os valores booleanos em valores inteiros
(h==5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
# duas condições simultâneas
(h>4) & (h<= 12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [41]:
# todos os elementos da matriz h que atendem o critério 
h[h>8]

array([ 9, 10, 11, 12, 13, 14])

In [42]:
# todos os elementos da matriz h que atendem aos dois critérios simultaneamente
h[(h>4)&(h<=12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
# todos os elementos da matriz h que atendem pelo menos um dos critérios
h[(h<4)|(h>=12)]

array([ 0,  1,  2,  3, 12, 13, 14])

`h>7`: array booleano

In [44]:
h>7

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

`h[h>7]`: indexação por uma condição lógica ou simplesmente indexação booleana

In [45]:
h[h>7]

array([ 8,  9, 10, 11, 12, 13, 14])

`np.where(h>7,'léo','yves')`: no array booleano `h>7`, nos elementos com valor lógico `False` é feita a substituição pela `string` `yves`, e nas entradas com valor lógico `True` é feita a substituição por `léo`.

In [46]:
np.where(h>7,'léo','yves')

array([['yves', 'yves', 'yves'],
       ['yves', 'yves', 'yves'],
       ['yves', 'yves', 'léo'],
       ['léo', 'léo', 'léo'],
       ['léo', 'léo', 'léo']], dtype='<U4')