# Introdução ao Numpy - 3
## Leonardo Yves de Souza Melo
### (21)971771433 | prof.leoyves@gmail.com
## Fontes:
### 1) Python for Data Analysis - Wes McKinney; capítulo 4
### 2) Python for Finance - Yves Hilspisch; capítulo 4

# Bibliotecas

In [1]:
import numpy as np

## Álgebra Linear no python 

In [2]:
x = np.arange(1,7).reshape((2,3))
y = np.array([[6,23],[-1,7],[8,9]])
display(x.shape,y.shape)

(2, 3)

(3, 2)

In [3]:
display(x,y)

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [4]:
# diferentes formas de calcular produto matricial 
display(x.dot(y),np.dot(x,y),x@y)

array([[ 28,  64],
       [ 67, 181]])

array([[ 28,  64],
       [ 67, 181]])

array([[ 28,  64],
       [ 67, 181]])

In [5]:
np.arange(1,5).reshape(4,1),np.eye(4)

(array([[1],
        [2],
        [3],
        [4]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [6]:
# produto matricial Ix=x (I é matriz identidade)
np.dot(np.eye(4),np.arange(1,5).reshape(4,1))

array([[1.],
       [2.],
       [3.],
       [4.]])

In [7]:
# produto matricial
np.eye(4)@np.arange(1,5).reshape(4,1)

array([[1.],
       [2.],
       [3.],
       [4.]])

`inv`: função que calcula o inverso de matrizes<br>
`qr`: calcula a decomposição QR

In [8]:
from numpy.linalg import inv,qr

In [9]:
X = np.random.randint(1,26,25).reshape((5,5))

In [10]:
X

array([[16,  1, 14, 25, 12],
       [ 1, 14, 19, 19, 21],
       [11, 22, 25, 20, 21],
       [18, 16,  9, 25,  6],
       [ 9, 17,  2,  1,  2]])

Produto matricial `mat=`$X^TX$

In [11]:
mat = X.T.dot(X)

In [12]:
mat

array([[ 783,  713,  698, 1098,  570],
       [ 713, 1226, 1008, 1148,  898],
       [ 698, 1008, 1267, 1438, 1150],
       [1098, 1148, 1438, 2012, 1271],
       [ 570,  898, 1150, 1271, 1066]])

In [13]:
# verificação da compatibilidade de métodos de multiplicação matricial
mat == X.T@X

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [14]:
# inversa da matriz 
inv(mat)

array([[ 0.02110187, -0.00635138, -0.02195612, -0.01383472,  0.03424855],
       [-0.00635138,  0.00435269,  0.00255969,  0.00432907, -0.00819355],
       [-0.02195612,  0.00255969,  0.08708989,  0.00637685, -0.09197181],
       [-0.01383472,  0.00432907,  0.00637685,  0.01213769, -0.01760047],
       [ 0.03424855, -0.00819355, -0.09197181, -0.01760047,  0.10973163]])

In [15]:
# verificação de que inv(mat) é de fato inversa de mat
mat.dot(inv(mat)),mat@inv(mat)

(array([[ 1.00000000e+00, -1.77635684e-15, -7.10542736e-15,
          0.00000000e+00,  1.42108547e-14],
        [ 3.55271368e-15,  1.00000000e+00,  1.42108547e-14,
          0.00000000e+00,  1.42108547e-14],
        [-7.10542736e-15,  0.00000000e+00,  1.00000000e+00,
          3.55271368e-15,  1.42108547e-14],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00, -1.77635684e-15,  0.00000000e+00,
          3.55271368e-15,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -1.77635684e-15, -7.10542736e-15,
          0.00000000e+00,  1.42108547e-14],
        [ 3.55271368e-15,  1.00000000e+00,  1.42108547e-14,
          0.00000000e+00,  1.42108547e-14],
        [-7.10542736e-15,  0.00000000e+00,  1.00000000e+00,
          3.55271368e-15,  1.42108547e-14],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00, -1.77635684e-15,  0.00000000e+00,
  

## Truncando os valores 
Nem o numpy nem as funções nativas do python inverteram as matrizes de maneira precisa.

Foi utilizada uma tolerância de 1e-13 para truncar os valores, junto com a indexação booleana, para realizar esse truncamento.

`t==np.eye(5)` compara a matriz `t` com a matriz indentidade dado que `t` é uma mariz do tipo $AA^{-1}$

In [16]:
t = mat@inv(mat)
t[t<1e-13]=0
t[t!=0]=1
t == np.eye(5)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
np.random.seed(42)
A = np.random.randint(-9,10,(5,5))
A

array([[-3,  5,  1, -2, -3],
       [ 9,  1,  1, -6, -2],
       [-7, -8,  2, -4, -8],
       [-9,  2,  2,  7,  0],
       [ 6,  5,  5,  9,  2]])

In [18]:
# np.diag(A): elementos da diagonal de A
# np.trace(A): soma dos elementos da diagonal principal de A
# np.sum(np.diag(A)) = np.trace(A)
display(np.diag(A),np.trace(A),np.sum(np.diag(A))==np.trace(A))

array([-3,  1,  2,  7,  2])

9

True

In [19]:
# np.linalg.inv(A): cálculo da inversa da matriz A
# np.linalg.pinv(X): cálculo da pseudoinversa da matriz X
np.linalg.inv(A),np.linalg.pinv(np.resize(A,(4,5)))

(array([[ 0.16483516, -0.33195971,  0.06593407, -0.42994505,  0.1790293 ],
        [ 0.18131868, -0.11515568, -0.02747253, -0.12293956,  0.04693223],
        [-0.78571429,  1.52678571, -0.21428571,  1.61607143, -0.50892857],
        [ 0.38461538, -0.83012821,  0.15384615, -0.83653846,  0.36217949],
        [-0.71428571,  1.20238095, -0.28571429,  1.32142857, -0.51190476]]),
 array([[-0.08104966,  0.12651796, -0.01792345,  0.06155158],
        [ 0.11686038,  0.00503348, -0.04945564,  0.00590547],
        [-0.08673478,  0.22346622,  0.02409698,  0.21888854],
        [-0.11281402,  0.09738032, -0.01579911,  0.15776803],
        [-0.01121861, -0.1085603 , -0.04593754, -0.08392498]]))

In [20]:
# decomposição QR da matriz A
q,r = np.linalg.qr(A)
display(q,r)

array([[-0.1875    , -0.56157784, -0.00955111,  0.72337752,  0.35511663],
       [ 0.5625    ,  0.11568657, -0.18863768,  0.52657921, -0.59777966],
       [-0.4375    ,  0.61827192, -0.56783125,  0.28935101,  0.14204665],
       [-0.5625    , -0.40988287, -0.25103291, -0.14480414, -0.65696577],
       [ 0.375     , -0.34782584, -0.76083819, -0.30781009,  0.25450025]])

array([[ 16.        ,   3.875     ,   0.25      ,  -1.8125    ,
          3.6875    ],
       [  0.        , -10.19727292,  -1.76824237,  -8.04366404,
         -4.18846665],
       [  0.        ,   0.        ,  -5.64010806,  -5.18252082,
          3.42690228],
       [  0.        ,   0.        ,   0.        ,  -9.54755416,
         -6.15371923],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         -0.49716328]])

In [21]:
# mostrando que a decomposição QR do numpy.linalg é aproximada
np.abs(q@r - A) < 1e-12

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [22]:
# decomposição SVD da matriz A
u,E,v_T = np.linalg.svd(A)
# transformando a matriz E numa matriz diagonal
e = np.eye(5)
e[e==1] = E

In [23]:
# verificação da precisão da decomposição
np.abs((u@e)@v_T - A) < 1e-12

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [24]:
# resolução de sistemas lineares utilizando diferentes formas de representar o 
# vetor X na equação Ax = b
np.linalg.solve(A,np.arange(1,6).reshape(5,1)),np.linalg.solve(A,np.arange(1,6))

(array([[-1.12591575],
        [-0.38850733],
        [ 5.54464286],
        [-2.34935897],
        [ 3.55952381]]),
 array([-1.12591575, -0.38850733,  5.54464286, -2.34935897,  3.55952381]))