# Introdução ao Numpy - 2
## Leonardo Yves de Souza Melo
### (21)971771433 | prof.leoyves@gmail.com
## Fontes:
### 1) Python for Data Analysis - Wes McKinney; capítulo 4
### 2) Python for Finance - Yves Hilspisch; capítulo 4

# Bibliotecas

In [1]:
import numpy as np

### Slicing and Indexing

In [2]:
# transformando todos os elementos de índice par em 12
arr = np.arange(10)
arr[::2] = 12
arr

array([12,  1, 12,  3, 12,  5, 12,  7, 12,  9])

In [3]:
# todas as mudanças ocorrem no array original
arr_slice = arr[5:8]
arr_slice[:] = 64
arr

array([12,  1, 12,  3, 12, 64, 64, 64, 12,  9])

In [4]:
# a utilização do método copy, garante que as alterações não estão sendo 
# realizadas no array original
arr_slice = arr[5:8].copy()
arr_slice[:] = 32
arr,arr_slice

(array([12,  1, 12,  3, 12, 64, 64, 64, 12,  9]), array([32, 32, 32]))

In [5]:
# esse array de duas dimensões pode ser pensado numa função em que cada 
# coordenada é um vetor de 3 dimenões
# f = (f1,f2,f3), fi: E -> R^3
arr2d = np.reshape(np.arange(1,10),(3,3))
# terceira coordenada
arr2d[2],arr2d.shape,arr2d.ndim

(array([7, 8, 9]), (3, 3), 2)

In [6]:
# primeira componente da terceira coordenada
# primeira linha e terceira coordenada da matriz
arr2d[0][2],arr2d[0,2]

(3, 3)

In [7]:
# array de 3 dimensões
arr3d = np.reshape(np.arange(1,13),(2,2,3))
arr3d,arr3d.shape,arr3d.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 (2, 2, 3),
 3)

In [8]:
"""
escolha das duas primeiras linhas em cada linha, seleciona os elementos com 
índice menor ou igual 1
"""
arr2d,arr2d[:2,1:]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[2, 3],
        [5, 6]]))

A operação `names == 'Bob'` retorna um array booleano. Note que o primeiro e o quarto elemento, são os únicos que retornaram `True`

In [9]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
names == 'Bob'

array([ True, False, False,  True, False, False, False])

Por meio da indexação booleana, podemos relacionar os arrays e nesse exemplo, selecionar a primeira e a quarta linha do array `data`, devido a atribuição feita por meio da operação <br>`names == 'Bob'`

Note que o número de linhas de `data` é igual ao shape de `names` e isso permite a indexação booleana

In [10]:
# seleção da 1º e da 4º linha
data,data[names == 'Bob']

(array([[-0.82057946,  0.92374595,  0.70940361, -0.85760034],
        [ 0.01992709, -0.45276677,  0.52700706,  0.00612724],
        [-0.16875137, -0.21397685, -0.30521948, -0.22144205],
        [ 0.86497152, -0.26185243, -0.00454527,  1.25723165],
        [ 1.43157946, -1.81179178,  0.7424955 , -1.31252425],
        [ 0.44873385,  0.15714218, -0.25664429,  0.22108487],
        [-0.40642317,  2.43907237,  0.45533087, -0.09928299]]),
 array([[-0.82057946,  0.92374595,  0.70940361, -0.85760034],
        [ 0.86497152, -0.26185243, -0.00454527,  1.25723165]]))

Essa indexação recupera as linhas 1 e 4 de `data` e para cada linha, sobram apenas os elementos de índice 2 em diante, ou seja, a terceira e a quarta coluna da matriz

In [11]:
data[names=='Bob',2:]

array([[ 0.70940361, -0.85760034],
       [-0.00454527,  1.25723165]])

In [12]:
# apenas as entradas de posição 4 de cada linha do array data[names=='Bob']
data[names=='Bob',3]

array([-0.85760034,  1.25723165])

In [13]:
# seleção de todas as linhas que não estavam no array data[names=='Bob']
# ~(names=='Bob') é a negação de names=='Bob'
data[~(names=='Bob')]

array([[ 0.01992709, -0.45276677,  0.52700706,  0.00612724],
       [-0.16875137, -0.21397685, -0.30521948, -0.22144205],
       [ 1.43157946, -1.81179178,  0.7424955 , -1.31252425],
       [ 0.44873385,  0.15714218, -0.25664429,  0.22108487],
       [-0.40642317,  2.43907237,  0.45533087, -0.09928299]])

In [14]:
# utilização do conectivo "ou" por meio do símbolo |
mask = (names=='Bob') | (names == 'Will')
mask.astype(int)

array([1, 0, 1, 1, 1, 0, 0])

In [15]:
data[mask]

array([[-0.82057946,  0.92374595,  0.70940361, -0.85760034],
       [-0.16875137, -0.21397685, -0.30521948, -0.22144205],
       [ 0.86497152, -0.26185243, -0.00454527,  1.25723165],
       [ 1.43157946, -1.81179178,  0.7424955 , -1.31252425]])

In [16]:
# mudando o valor de todas as entradas negativas para 0
data[data<0] = 0
data

array([[0.        , 0.92374595, 0.70940361, 0.        ],
       [0.01992709, 0.        , 0.52700706, 0.00612724],
       [0.        , 0.        , 0.        , 0.        ],
       [0.86497152, 0.        , 0.        , 1.25723165],
       [1.43157946, 0.        , 0.7424955 , 0.        ],
       [0.44873385, 0.15714218, 0.        , 0.22108487],
       [0.        , 2.43907237, 0.45533087, 0.        ]])

In [17]:
# utilizando o indexador names != 'Joe' para alterar os valores do array
data[names != 'Joe'] = 7
data

array([[7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [1.99270917e-02, 0.00000000e+00, 5.27007057e-01, 6.12724077e-03],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [4.48733849e-01, 1.57142181e-01, 0.00000000e+00, 2.21084870e-01],
       [0.00000000e+00, 2.43907237e+00, 4.55330868e-01, 0.00000000e+00]])

In [18]:
# gerador de 1000 pontos equidistantes entre 0 e 1
points = np.arange(-5,5,0.01)
len(points)

1000

In [19]:
q,w = np.arange(10),np.arange(-9,1)
e,r = np.meshgrid(q,w)

O ``np.meshgrid()`` possibilita a construção de duas matrizes quadradas de mesmas dimensões, em que a primeira é simplesmente repetições do array do primeiro argumento em todas as **linhas** <br>
A segunda matriz repete os elementos do segundo argumento da função, nas colunas da matriz

In [20]:
e,r,r.shape,e.shape

(array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[-9, -9, -9, -9, -9, -9, -9, -9, -9, -9],
        [-8, -8, -8, -8, -8, -8, -8, -8, -8, -8],
        [-7, -7, -7, -7, -7, -7, -7, -7, -7, -7],
        [-6, -6, -6, -6, -6, -6, -6, -6, -6, -6],
        [-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
        [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
        [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
        [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]]),
 (10, 10),
 (10, 10))

In [21]:
X = np.random.randn(1000)
# número de valores positivos
(X>0).sum()

489

In [22]:
# tranformando numa matriz aleatória binária
X[X>=0]=1
X[X<0]=0
X.astype('?')

array([ True, False, False, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True,  True,  True, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True, False, False, False, False,  True,
        True,  True,  True, False, False,  True, False, False,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True, False,  True, False, False, False,  True,
        True, False, False, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True, False, False,  True, False, False,  True, False,
        True,  True, False, False,  True, False, False,  True, False,
       False, False,  True, False, False,  True, False,  True,  True,
       False, False, False, False, False,  True,  True,  True,  True,
       False, False,

``np.all()``: usado pra verificar se todos os valores num array booleano são `True`ou não <br>
`np.any()`: é utilizado para verificar se pelo menos um ou mais valores são `True`ou não num dado array booleano

In [23]:
X.any(),X.all()

(True, False)

In [24]:
np.array([True,True,True]).any(),np.array([True,True,True]).all()

(True, True)

In [25]:
np.array([True,True,False]).any(),np.array([True,True,False]).all()

(True, False)